;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        beginning-of-visual-line
        go-mode-insert-and-indent
        helm-M-x
        helm-show-kill-ring
        indent-for-tab-command
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        lua-electric-match
        markdown-cycle
        markdown-exdent-or-delete
        move-text-up
        org-beginning-of-line
        org-self-insert-command
        py-indent-line
        ))

(setq mc/cmds-to-run-once
      '(
        ignore
        keyboard-escape-quit
        racer-complete-or-indent
        sh-execute-region
        sp-remove-active-pair-overlay
        ))
