;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        indent-for-tab-command
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        markdown-exdent-or-delete
        py-indent-line
        ))

(setq mc/cmds-to-run-once
      '(
        keyboard-escape-quit
        markdown-cycle
        sp-remove-active-pair-overlay
        ))
